### ISSUE TITLE
OSError and EOFError

### ISSUE THREAD

**Issue by wlpku123** [uvipen/Super-mario-bros-PPO-pytorch#10]
File "E:\anaconda\lib\multiprocessing\connection.py", line 170, in fileno
    self._check_closed()
  File "E:\anaconda\lib\multiprocessing\connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\anaconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by jiangminmin** [comment]
That happened to me, too. please tell me how you solved it.

**Comment by imkeithyang** [comment]
same issue here, no idea how to solve it

**Comment by wlpku123** [comment]
use linux to deal it&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年11月3日(星期二) 下午2:30
收件人: "uvipen/Super-mario-bros-PPO-pytorch"<Super-mario-bros-PPO-pytorch@noreply.github.com&gt;; 
抄送: "immigration office"<763764784@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [uvipen/Super-mario-bros-PPO-pytorch] OSError and EOFError (#10)





 
same issue here, no idea how to solve it
