### ISSUE TITLE
'gym_super_mario_bros' not found

### ISSUE THREAD

**Issue by ghost** [uvipen/Super-mario-bros-PPO-pytorch#3]
I tried to run train getting this error. 

```
(env_pytorch) c:\GitHub\uvipen\Super-mario-bros-PPO-pytorch>conda deactivate

(base) c:\GitHub\uvipen\Super-mario-bros-PPO-pytorch>python train.py --world 5 --stage 2 --lr 1e-4
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from src.env import MultipleEnvironments
  File "c:\GitHub\uvipen\Super-mario-bros-PPO-pytorch\src\env.py", line 5, in <module>
    import gym_super_mario_bros
ModuleNotFoundError: No module named 'gym_super_mario_bros'

**Comment by vietnh1009** [comment]
https://pypi.org/project/gym-super-mario-bros/
Please read README to install necessary libraries or use my Docker
