### ISSUE TITLE
`OSError: handle is closed` during training

### ISSUE THREAD

**Issue by maartenvanhooft** [uvipen/Super-mario-bros-PPO-pytorch#7]
First of all, thanks for this project!

I'm able to run it during the test phase, but not for the train phase. I'm encountering:

```
C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\Scripts\python.exe C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py --world 5 --stage 2 --lr 1e-4
Traceback (most recent call last):
  File "C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py", line 154, in <module>
    train(opt)
  File "C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py", line 55, in train
    envs = MultipleEnvironments(opt.world, opt.stage, opt.action_type, opt.num_processes)
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\src\env.py", line 122, in __init__
    process.start()
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 939, in reduce_pipe_connection
    dh = reduction.DupHandle(conn.fileno(), access)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 170, in fileno
    self._check_closed()
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

When setting the number of processes to 1:

```

C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\Scripts\python.exe C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\src\env.py", line 135, in run
    self.env_conns[index].send(self.envs[index].reset())
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\src\env.py", line 92, in reset
    state = self.env.reset()
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\src\env.py", line 65, in reset
    return process_frame(self.env.reset())
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\lib\site-packages\nes_py\wrappers\joypad_space.py", line 78, in reset
    return self.env.reset()
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\lib\site-packages\gym\wrappers\time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\lib\site-packages\nes_py\nes_env.py", line 258, in reset
    self._restore()
  File "C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch\venv\lib\site-packages\nes_py\nes_env.py", line 220, in _restore
    _LIB.Restore(self._env)
OSError: exception: access violation reading 0x0000020D6BE8F220
Traceback (most recent call last):
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py", line 154, in <module>
    train(opt)
  File "C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py", line 64, in train
    curr_states = [agent_conn.recv() for agent_conn in envs.agent_conns]
  File "C:/Users/maarten/PycharmProjects/Super-mario-bros-PPO-pytorch/train.py", line 64, in <listcomp>
    curr_states = [agent_conn.recv() for agent_conn in envs.agent_conns]
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\maarten\AppData\Local\Programs\Python\Python36\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

```

I'm on Python 3.6 in combination with Windows 10. I resolved my dependencies using:

```
pip install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
pip install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl
pip install gym-super-mario-bros
pip install opencv-python
choco install ffmpeg
```

Package versions : 

```
(venv) C:\Users\maarten\PycharmProjects\Super-mario-bros-PPO-pytorch>pip list
Package              Version
-------------------- --------
cloudpickle          1.3.0
gym                  0.17.2
gym-super-mario-bros 7.3.2
nes-py               8.1.4
numpy                1.19.1
opencv-python        4.4.0.40
Pillow               7.2.0
pip                  19.0.3
pyglet               1.5.7
scipy                1.5.2
setuptools           40.8.0
six                  1.15.0
torch                1.1.0
torchvision          0.3.0
tqdm                 4.48.2


```

Any ideas?

**Comment by vietnh1009** [comment]
Hi,
I didnt meet this error before. I did this project on Ubuntu, and have never run it on win. Could you pls try on ubuntu?

**Comment by maartenvanhooft** [comment]
Got it, thanks!
